# Generated by Django 5.1.1 on 2024-10-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_position',
            field=models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Home Banner'), (2, 'Product Banner'), (3, 'Cart Banner'), (4, 'Order Banner')], default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_status',
            field=models.IntegerField(choices=[(1, 'Live'), (0, 'Delete')], default=1),
        ),
    ]
