# Generated by Django 5.1.1 on 2024-10-01 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=120, null=True)),
                ('city', models.CharField(max_length=120, null=True)),
                ('district', models.CharField(max_length=120, null=True)),
                ('state', models.CharField(max_length=120, null=True)),
                ('country', models.CharField(max_length=120, null=True)),
                ('land_mask', models.CharField(max_length=120, null=True)),
                ('pincode', models.CharField(max_length=120, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='customers.userprofile')),
            ],
        ),
    ]
