# Generated by Django 5.1.1 on 2024-10-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_userprofile_name_alter_userprofile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='land_mask',
            new_name='land_mark',
        ),
    ]
