# Generated by Django 5.1.1 on 2024-10-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_status',
            field=models.IntegerField(choices=[(2, 'pay_now'), (1, 'cod')], default=0, null=True),
        ),
    ]
