# Generated by Django 5.1.1 on 2024-11-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_stage',
            field=models.IntegerField(choices=[(1, 'order_confirmed'), (2, 'order_processing'), (3, 'order_delivered'), (4, 'order_cancel_requested'), (-1, 'order_canceled')], default=0),
        ),
    ]
